_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.13.1
            "5": 0.19.9
            "6": 4.48.3
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
architecture:
    value: SimpleRegressor
dataset:
    value: SMILES_Big_Data_Set
epochs:
    value: 20
learning_rate:
    value: 0.001
